export const FETCH_CARDS_REQUEST = 'FETCH-CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAIL = 'FETCH_CARDS_FAIL';
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CARD = 'REMOVE_FROM_CARD'
export const ADD_TO_FAV = 'ADD_TO_FAV'
export const REMOVE_FROM_FAV = 'REMOVE_FROM_FAV'